sudo: required

language: node_js

node_js:
  - 10

services:
  - docker

before_install:
  - docker build -t jordhancarvalho/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true jordhancarvalho/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-1-007008111373"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
